### ISSUE TITLE
conda_gen_env

### ISSUE THREAD

**Issue by skon7** [andresberejnoi/PublicNotebooks#1]
When running the command `python conda_export.py --from-history --use-versions -o environment.yml` , an unexpected output is generated, missing information about the pip packages. The generated `environment.yml` didn't contain pip packages.
```
channels:
- conda-forge
- defaults
dependencies:
- console_shortcut=0.1.1
- fastapi=0.97.0
- joblib=1.2.0
- jupyterlab=4.0.2
- numpy=1.24.3
- pylint=2.17.4
- pymongo=4.3.3
- python=3.9.16
name: env_name
prefix: prefix
```
I took the provided code and made some modifications to address the issue. Here's the updated `environment.yml` file that includes the rectifications and additions based on [my code](https://github.com/skanderhaddad/conda_env_export/tree/main):
```
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- numpy
- joblib
- fastapi
- pymongo
- pylint
- jupyterlab
- console_shortcut
- pip:
  - click==8.1.3
  - h11==0.14.0
  - python-dotenv==1.0.0
  - ruamel-yaml==0.17.32
  - ruamel-yaml-clib==0.2.7
  - scikit-learn==1.2.2
  - scipy==1.10.1
  - threadpoolctl==3.1.0
  - uvicorn==0.22.0
```

**Comment by andresberejnoi** [comment]
Thank you for pointing this out. I looked at my code and realized that I accidentally left out the part of the code that adds the pip dependencies section when those two flags ( `--from-history` and `--use-versions` ) are used together. I will probably create a new repository only for this conda script and other conda related topics. So it is easier to track.

I'll include a link to this issue there.

**Comment by andresberejnoi** [comment]
Here is the link for the newly created repository:
[https://github.com/andresberejnoi/Conda-Tools](https://github.com/andresberejnoi/Conda-Tools)

**Comment by skon7** [comment]
Thank you for your active engagement and valuable input. I genuinely appreciate your efforts.
